// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdkhjSErCkBSstq_xfpVvHV88NOCumnWc',
    appId: '1:520124966282:web:4ab2d27a4cf1280a8b5473',
    messagingSenderId: '520124966282',
    projectId: 'finflex-ebanking',
    authDomain: 'finflex-ebanking.firebaseapp.com',
    storageBucket: 'finflex-ebanking.appspot.com',
    measurementId: 'G-Z60ZSQLZ8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7IxnQDIJ9S9Z5GypEZgSq-m3R8S-dg8',
    appId: '1:520124966282:android:bd74e336eba406a18b5473',
    messagingSenderId: '520124966282',
    projectId: 'finflex-ebanking',
    storageBucket: 'finflex-ebanking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdiTQkb1QxYxfY_ZFmWsotz79VQ6HdBQE',
    appId: '1:520124966282:ios:c51c21ca75905de48b5473',
    messagingSenderId: '520124966282',
    projectId: 'finflex-ebanking',
    storageBucket: 'finflex-ebanking.appspot.com',
    iosBundleId: 'com.example.finflex',
  );
}
